### ISSUE TITLE
Vercel template fail to deploy

### ISSUE THREAD

**Issue by mw19930312** [datastax/ragbot-starter#17]
Hi, I'm following the [deployment template](https://vercel.com/new/wei-miaos-projects/templates/next.js/ragbot-starter) from Vercel. I saw an error of ``not able to find https://github.com/datastax/ragbot-starter#start``. I tried to leave the root directory of Vercel project to be empty. However, I encountered another error that ``the output directory of `public` is not found``.

How should I revise Vercel deployment settings to move forward then?

**Comment by mfortman11** [comment]
Hey @mw19930312 there appears to be an issue w/ the deployment template link at the moment. Give this one a try: https://vercel.com/new/clone?repository-url=https://github.com/datastax/ragbot-starter&env=ASTRA_DB_NAMESPACE,OPENAI_API_KEY,ASTRA_DB_ID,ASTRA_DB_REGION,ASTRA_DB_APPLICATION_TOKEN

**Comment by mfortman11** [comment]
This was fixed in Vercel as well give it another shot!

**Comment by mfortman11** [comment]
This was fixed in Vercel as well give it another shot!
