### ISSUE TITLE
Error openAI apiKey

### ISSUE THREAD

**Issue by mateusloubach** [datastax/ragbot-starter#20]
delete

**Comment by mfortman11** [comment]
@mateusloubach looks like you're missing the `OPEN_API_KEY` variable
If you don't yet have an OpenAI account you can create one [here](https://platform.openai.com/signup)
Then go to https://platform.openai.com/api-keys to create a key

When running locally you can add your key to a `.env` file with `OPENAI_API_KEY={YOUR KEY}`
And in Vercel you can add it to the deployment under Settings > environment variables

**Comment by mateusloubach** [comment]
I have an OpenAI account, I created an OpenAi ApiKey and I followed the steps. but it isn't being recognized in the .env file. - I looked for another way to insert it and it tells me to change this:
```
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});
```

I tried a couple of things, but nothing too deeply thought out.. - I'll invest a couple of hours after work to see how to solve it.

**Comment by mfortman11** [comment]
a `.env` in the root of the project should do the trick. Another option would be to set the env variable in the command line using `export OPENAI_API_KEY=YOURKEY`

**Comment by mateusloubach** [comment]
hi, this can issue be discarded and deleted. thank you
