### ISSUE TITLE
Chat responses are interrupted on Vercel

### ISSUE THREAD

**Issue by mw19930312** [datastax/ragbot-starter#22]
Hi,

I recently noticed that the production chatbot on Vercel was not able to give a complete answer. Everything tested fine locally that I was able to generate much longer responses. However, the incomplete answer issue consistently occurs on Vercel. Is there anything different between Vercel and local? Is there anything that I can change from the code to avoid this?

Here is a screenshot of the incomplete answer:
<img width="760" alt="Screenshot 2024-01-25 at 12 00 58 AM" src="https://github.com/datastax/ragbot-starter/assets/16345944/3c3d521a-9f75-4a4d-b2b0-8d7d711426ce">

**Comment by mw19930312** [comment]
Is this related to OpenAIStream or StreamingTextResponse used in the project? Or is it something that I need to deal with Vercel?

**Comment by mfortman11** [comment]
@mw19930312 are you seeing this at https://ragbot-starter.vercel.app/ or your deployment?

**Comment by mw19930312** [comment]
@mfortman11 Thanks for the reply! I'm seeing this on my deployment. However, this starts only recently after I pushed a PR that changes the system prompt. Can it be any Vercel issue? Or is it just the response is too long?

**Comment by mfortman11** [comment]
It could be a Vercel issue, hobby accounts have a 10s timeout limit.
However if you are seeing timeouts before their limit it hit you could set an OpenAI timeout
```javascript
const response = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      stream: true,
      messages: [...ragPrompt, ...messages],
    }, {
      timeout: 10000,
    });
```

**Comment by mw19930312** [comment]
@mfortman11 Thanks! Let me give it a try.

Just for more context, what is this 10s timeout limit applied to? Is it between two openAI api calls? In my latest PR, I did add another API call as a query planner.

**Comment by mfortman11** [comment]
It is for the serverless function's runtime. So the entirety of the post call

**Comment by mw19930312** [comment]
@mfortman11 Thanks for the explanation! If it is the POST call duration, then setting a timeout in the OpenAI request does not work, right? It is actually one of my POST calls takes more than 10 seconds to finish so that the execution terminated. In the POST call of Send button, I did add another OpenAI API call for a query planner so that such POST call is taking way longer than before. Is there any solution other than upgrading to the Pro tier on Vercel?

**Comment by mfortman11** [comment]
I don't believe so the only other option would be finding another hosting solution.

**Comment by mfortman11** [comment]
The other thing you can do to improve the speed of the llm call would be to sure you're using a turbo version of the llm
